#spring.datasource.url=jdbc:mysql://localhost/db_buencreyente?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# microservicio-buencreyente configuration
server:
  port: 8080 #set your port
  
# Spring Boot configuration
spring:
  application:
    name: app_user
  
  # Database
  datasource:
   #Database Desarrollo con @Id universales
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_usuarios?useSSL=false
    username: root
    password: 789Administrador
    
  # JPA properties
  jpa:
    hibernate:
      #enable_lazy_load_no_trans: true
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    #properties hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    #database-platform: org.hibernate.dialect.MySQL55Dialect
    open-in-view: false
    generate-ddl: true
    
#https://github.com/nydiarra/springboot-jwt
#Colocamos valores que nosotros querramos
security:
  jwt:
    scope-read: read
    resource-ids: appusersresourceid
    client-secret: 789Administrador
    client-id: app_users
    grant-type: password
    scope-write: write
  security-realm: Spring Boot JWT
  signing-key: MaYzkSjmkzPC57L
  oauth2:
    resource:
      filter-order: '3'
  encoding-strength: '256'
   
  
logging:
  level:
    org:
      hibernate:
        #sql: debug
        #type: trace
